name: eltyp_delivery
description: "الطيب لخدمات النقل - تطبيق Flutter لإدارة خدمات النقل والتوصيل"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+15

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Config
  # TODO: IOS
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  get_it: ^9.1.1
  upgrader: ^12.3.0
  dartz: ^0.10.1
  easy_debounce: ^2.0.3
  internet_connection_checker_plus: ^2.9.1
  flutter_inappwebview: ^6.1.5
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  path: ^1.9.1

  # UI Packages
  step_progress_indicator: ^1.0.2
  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^9.0.0
  flutter_rating_bar: ^4.0.1
  animate_do: ^4.2.0
  pin_code_fields: ^8.0.1
  calendar_date_picker2: ^2.0.1
  skeletonizer: ^2.1.1
  google_nav_bar: ^5.0.7
  intl_phone_field: ^3.2.0
  slide_to_act: ^2.0.2
  google_fonts: ^6.3.3
  audioplayers: ^6.5.1
  marqueer: ^2.1.0
  flutter_spinkit: ^5.2.2
  # permission handler
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  file_picker: ^10.3.7

  # State Management
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1

  # Local Storage
  flutter_secure_storage: ^9.2.4

  # Network
  dio: ^5.9.0
  # talker_dio_logger: ^4.7.5
  url_launcher: ^6.3.2
  pretty_dio_logger: ^1.4.0
  pusher_channels_flutter:
    git:
      url: https://github.com/hamzamirai/pusher-channels-flutter.git

  # Firebase & Notifications
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  http: ^1.6.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/splash_android_12.png
  color: "#2F2E2E"
  image_dark: assets/images/splash_android_12.png
  color_dark: "#2F2E2E"
  android: true
  ios: true

  android_12:
    image: assets/images/splash_android_12.png
    color: "#2F2E2E"
    image_dark: assets/images/splash_android_12.png
    color_dark: "#2F2E2E"

# dart run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/translation/
    - assets/fonts/cairo/
    - assets/
    - assets/images/app_logo.png
    - assets/images/auth_image.png
    # - assets/sound/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900

    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Black.ttf

        - asset: assets/fonts/cairo/Cairo-Bold.ttf

        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf

        - asset: assets/fonts/cairo/Cairo-Medium.ttf

        - asset: assets/fonts/cairo/Cairo-Regular.ttf

        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf

        - asset: assets/fonts/cairo/Cairo-Light.ttf
